### ISSUE TITLE
Feature Request: Please provide a link to the sub-release after created (from parent release).

### ISSUE THREAD

**Issue by adf2112** [xebialabs-community/xlr-xlrelease-plugin#10]
When the users sees a sub-release from the running release - it is a bit difficult for them to switch to the sub-release so they can see progress or interact with the release from the XLR dashboard.  
It would be cool if there was some way to show a link to the sub release so they could click on it to see the sub release without navigating away from the parent release.
Thank you!

**Comment by jdewinne** [comment]
Sorry for the late reply. As you might have noticed, creating a sub release is now standard available. Would it be possible for you to switch to the [create release task](https://docs.xebialabs.com/xl-release/how-to/create-a-create-release-task.html), which has this feature as part of the comments?

**Comment by jdewinne** [comment]
Done: See [v2.1.0](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.1.0)
