### ISSUE TITLE
Delete Phase Task not working

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xlrelease-plugin#17]
Hi There,

I am getting failures with the deleting phases in version 1.80.   It almost seems like it is passing an invalid phase id to the delete_phase method.   I get the following error since upgrading.

Found matching phase [phase 2] for deletion.
Failed to delete phase with id [Applications/Release7715303/Phase7622524]
Status: 404
Response: RESTEASY003210: Could not find resource for full path: http://dev-m-20srk:5516/phases/Applications/Release7715303/Phase7622524

Am I missing something?   

Thanks,
Bernie

**Comment by bbonn** [comment]
FYI

I looked at what the old version was passing as a phase id and it is in this format Release7715303-Phase2278960, as opposed to Applications/Release7715303/Phase7622524.

**Comment by jdewinne** [comment]
Hi Bernie,

Thanks for reporting. I've fixed it in version [v1.9.0](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v1.9.0).
I've also added an additional option to specify the phases as a `set_of_string`, instead of the comma separated list.

Regards,
Joris
