### ISSUE TITLE
Not able to Find a Template with Create New Release step

### ISSUE THREAD

**Issue by jashan05** [xebialabs-community/xlr-xlrelease-plugin#21]
We are using "Create and Start Sub release" task and we are not able to find the Template. Everytime it says that It can not find a Template.

We are trying to invoke a template like below format:
Application Name(Folder) -> Template Name

e.g 
urlforxlr/api/v1/templates/Applications/Folder14197243/Release955718424/create

**Comment by jdewinne** [comment]
At this moment this plugin doesn't support "Folders". A workaround might be to switch to the official task to Create a sub release: https://docs.xebialabs.com/xl-release/how-to/create-a-create-release-task.html

Would that work?

**Comment by Stargirly2** [comment]
I use it succesfully

**Comment by brhahlen** [comment]
Fixed in #22
