### ISSUE TITLE
Create and start release task fails with xlr 7.x.x

### ISSUE THREAD

**Issue by difoul** [xebialabs-community/xlr-xlrelease-plugin#23]
The URI for searching a template by name is 
/api/v1/templates?**title**=TEMPLATE_NAME
instead of 
/api/v1/templates?**filter**=TEMPLATE_NAME

Doc :
https://docs.xebialabs.com/xl-release/7.2.x/rest-docs/#listing-templates

**Comment by jdewinne** [comment]
Fixed on master (after some big refactoring)

**Comment by brhahlen** [comment]
There is something going wrong when testing the latest code on version 7.0.1 of XLR.
I always get back ``` Going to use xlr_api_url: /api/v1/templates?filter=Testing Failed to find template in XL Release ```, even when changing the code to use ```/api/v1/templates?title=TEMPLATE_NAME```

Using a REST call myself, returns the template properly, so there seems to be something going wrong in the parsing of the response, but I can't figure out what, at the moment.

Needs some more testing

**Comment by brhahlen** [comment]
Okay, never mind, this was my own screw-up...

**Comment by jdewinne** [comment]
Can you try with [v2.0.0](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.0.0).
