### ISSUE TITLE
Automated Password not Set in sub release created out of xlr.CreateAndStartSubRelease task

### ISSUE THREAD

**Issue by ashudoda** [xebialabs-community/xlr-xlrelease-plugin#30]
Dear Associate,

We are using sub release from within a XLR Template. The sub release is created from xlr-xlr plugin task "Xlr: Create and Start Sub Release". The Sub Release template has already Automated User Credentials Set, but when a release is created out of this template, the automated credentials are wiped off. Please help to provide resolution for this.

Regards,
Ashish

**Comment by jdewinne** [comment]
What version of XLR and what version of the plugin is being used?

**Comment by ashudoda** [comment]
we are using 2.3.0 version.

Is this fixed in 2.3.2 ?

**Comment by jdewinne** [comment]
[v2.3.1](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.3.1) and [v2.3.2](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.3.2) are only adding new features. Sorry for the incorrect versioning.
As they are not fixing anything, can you also let us know which version of XLR you're using so we can try to reproduce?

**Comment by jdewinne** [comment]
I was able to reproduce. Fixed in [v2.3.3](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.3.3)
