### ISSUE TITLE
Link for Sub Release is not correct

### ISSUE THREAD

**Issue by ashudoda** [xebialabs-community/xlr-xlrelease-plugin#32]
Dear Associate,

We are using latest 2.3.3 plugin to test for automated password not set issue. The issue seems to be fixed with the latest version. Thanks !!!

Now we have observed a minor issue, when a sub release is started with the plugin task SubRelease, we see a wrong hyperlink of the sub-release :

Going to use xlr_api_url: /api/v1/templates?title=CSV Export Found template CSV Export with id Applications/Folder811086502/Release139636783 Sending content {"releaseTitle" : "testjw", "releaseVariables" : {}, "scheduledStartDate" : null, "autoStart" : true }

**Created Applications/Folder811086502/Releaseaa758c1b4d4a44838fad0f9e9e5b1adf in XLR**

it should be : 
**Created Applications/Folder811086502-Releaseaa758c1b4d4a44838fad0f9e9e5b1adf in XLR**

Notice a "/" instead of "-"

Please see if this can be corrected.

Regards,
Ashish

**Comment by ashudoda** [comment]
A pull request is open for this issue.

https://github.com/xebialabs-community/xlr-xlrelease-plugin/pull/33

Regards,
Ashish

**Comment by jdewinne** [comment]
See [v2.3.4](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.3.4)
