### ISSUE TITLE
Adding gate task dependency fails possibly due to internal api no longer being available. 

### ISSUE THREAD

**Issue by ankurtrivedi** [xebialabs-community/xlr-xlrelease-plugin#36]
https://github.com/xebialabs-community/xlr-xlrelease-plugin/blob/80a35754b5654c60ac5a28279b787e4fc91ecd55/src/main/resources/xlr/XLReleaseClient.py#L134

**Comment by vdoulcier** [comment]
#41 Sorry for duplicate entry.
Waiting for a merge / release.

**Comment by sblin** [comment]
Merged
