### ISSUE TITLE
Add dependency doesn't work when creating async subrelease

### ISSUE THREAD

**Issue by vdoulcier** [xebialabs-community/xlr-xlrelease-plugin#40]
Hello,

When using the sub-release task, the add_dependency feature doesn't work (it added nothing in the planned Gate task, but no error is thrown).

Looking at the method in the XLReleaseClient class:
https://github.com/xebialabs-community/xlr-xlrelease-plugin/blob/master/src/main/resources/xlr/XLReleaseClient.py#L133

I see that a "releaseId" field is used in the content with the ID:
`content = {"target": {"releaseId": dependency_release_id}}`
But when I take a look at the Gate configuration tile in the current XL Release version (9.0.6), I have something like:
`gate('myGate') { dependencies { dependency { target {  release 'My Sub Release' } } } }`

Maybe "releaseId" should be replaced by "release" + sub-release name?

Thank's for your help.

Regards,
Valentin

**Comment by vdoulcier** [comment]
#41 Edit.
I fixed it by switching the the public API.

**Comment by sblin** [comment]
Merged
