### ISSUE TITLE
Password variables are not supported (resolved) when sent from a parent relase

### ISSUE THREAD

**Issue by adf2112** [xebialabs-community/xlr-xlrelease-plugin#9]
Hi. This might be a feature request instead...
When starting a sub release, a password variable from the parent release is not resolved and therefore not sent to the sub-release.
Xebia suggested that I file an issue.
Thank you!

**Comment by jdewinne** [comment]
Sorry for the late reply. As you might have noticed, creating a sub release is now standard available. Would it be possible for you to switch to the [create release task](https://docs.xebialabs.com/xl-release/how-to/create-a-create-release-task.html)?

**Comment by jdewinne** [comment]
I've just tested this with [v2.0.0](https://github.com/xebialabs-community/xlr-xlrelease-plugin/releases/tag/v2.0.0) on XLR 7.5. Works. Can you try if not migrated to the supported plugin?
